import Reveal from "./Reveal";
import { ArrowUpRight, Check, Quote } from "lucide-react";

const sports=["Archery","Cycling","Hockey","Swimming","Taekwondo","Football","Horse Riding","Billiards","Squash","Volleyball","Basketball","Cricket","Lawn Tennis","Badminton","Table Tennis"];
const reviews=[
 ["Tashi Tsering","F/O Jigmet Skaldon","I would like to convey a big thanks to the Management and Teachers of Tulas International School for taking good care of my son."],
 ["Namita Agarwal","M/O Krishna Agarwal","Tulas gives a comprehensive environment for our child to grow. The sports, academics, and extra-curricular activities have helped Krishna in knowing himself better."],
 ["Sandeep Kumar","F/O Aryan","Our experience is very amazing with school. Staff is very cooperative and supportive. Our son always admires the school whenever we talk with him."],
];
export function Hero(){return <section className="hero" id="top"><div className="hero-glow"/><div className="container hero-grid"><div className="hero-copy"><Reveal><div className="eyebrow"><span/> DEHRADUN · UTTARAKHAND</div><h1>Where curiosity <em>becomes</em> character.</h1><p>TIS is one of India’s top boarding and day schools in Dehradun, focused on academic excellence, holistic development, and preparing students to be global leaders.</p><div className="hero-actions"><a className="button primary" href="https://admission.tis.edu.in/" target="_blank" rel="noreferrer">Begin your Tulas journey <ArrowUpRight size={18}/></a><a className="text-link" href="#about">Discover TIS <span>↓</span></a></div></Reveal></div><Reveal delay={.12} className="hero-visual"><div className="hero-photo"><div className="photo-label"><span>22 acres</span><small>pollution-free campus</small></div></div><div className="floating-note"><span>16+</span><small>Olympic sports</small></div></Reveal></div><div className="scroll-cue">SCROLL TO EXPLORE <span>↓</span></div></section>}

export function Intro(){return <section className="section intro" id="about"><div className="container"><Reveal><p className="kicker">01 — THE TULAS APPROACH</p><h2>School isn’t just about lessons. <span>It’s about endless opportunities waiting to be explored.</span></h2></Reveal><div className="intro-bottom"><Reveal delay={.08}><p>Tulas International School was established in 2012 under the aegis of Rishabh Educational Trust to impart education through seamless opportunities.</p><a className="text-link" href="#academics">How we teach <span>↗</span></a></Reveal><Reveal delay={.16}><div className="mini-card"><div className="mini-icon">✦</div><div><strong>Academic + holistic</strong><p>Learning that develops confidence, curiosity and character.</p></div></div></Reveal></div></div></section>}

export function Stats(){const stats=[["22","ACRE POLLUTION-FREE CAMPUS"],["16+","OLYMPIC SPORTS"],["24/7","MEDICAL ASSISTANCE"],["6:1","STUDENT TEACHER RATIO"]];return <section className="stats"><div className="container stats-grid">{stats.map(([n,l],i)=><Reveal key={l} delay={i*.05}><div className="stat"><span>{n}</span><p>{l}</p></div></Reveal>)}</div></section>}

export function Academics(){return <section className="section dark-section" id="academics"><div className="container"><Reveal><p className="kicker light">02 — ACADEMICS</p><div className="section-head"><h2>A curriculum built for <em>the world ahead.</em></h2><p>Our CBSE curriculum prioritises reasoning and analytical thinking over rote memorisation, with project-based, art-integrated and experiential learning.</p></div></Reveal><div className="feature-grid"><Reveal><article className="feature large"><span className="feature-no">01</span><h3>Digital advantage</h3><p>Digital classrooms, VR simulators and online assessment tools create engaging learning experiences.</p><a href="https://tis.edu.in/academics/affilation/" target="_blank" rel="noreferrer">Explore curriculum <ArrowUpRight/></a></article></Reveal><Reveal delay={.08}><article className="feature"><span className="feature-no">02</span><h3>Experiential learning</h3><p>Educational trips, science quests, seminars and business conclaves connect classroom knowledge with real life.</p></article></Reveal><Reveal delay={.16}><article className="feature"><span className="feature-no">03</span><h3>Competitive edge</h3><p>Olympiads and dedicated IIT-JEE/NEET preparation help students build confidence for what comes next.</p></article></Reveal></div></div></section>}

export function Life(){return <section className="section life" id="life"><div className="container life-grid"><Reveal className="life-image"><div className="image-card"><div><span>BEYOND</span><strong>THE<br/>CLASSROOM</strong></div></div></Reveal><Reveal delay={.1}><p className="kicker">03 — LIFE AT TULAS</p><h2>Make learning feel like an <em>adventure.</em></h2><p className="body-copy">When students are inspired, they don’t just learn—they grow, explore, and shape their own futures. At Tulas, creativity, leadership and lifelong learning live alongside academics.</p><ul className="check-list"><li><Check/> Nurturing boarding environment</li><li><Check/> Leadership and innovation</li><li><Check/> Music, art, drama and activities</li></ul><a className="button outline" href="https://tis.edu.in/" target="_blank" rel="noreferrer">Explore campus <ArrowUpRight/></a></Reveal></div></section>}

export function Sports(){return <section className="section sports" id="sports"><div className="container"><Reveal><p className="kicker">04 — BEYOND ACADEMICS</p><div className="section-head"><h2>16+ sports. <em>One confident student.</em></h2><p>It’s not just a facility. At Tulas it’s the foundation—bringing joy, discipline and teamwork into everyday school life.</p></div></Reveal><div className="sport-list">{sports.map((s,i)=><Reveal key={s} delay={(i%5)*.03}><div className="sport-item"><span>{String(i+1).padStart(2,"0")}</span><strong>{s}</strong><ArrowUpRight/></div></Reveal>)}</div></div></section>}

export function Stories(){return <section className="section stories" id="stories"><div className="container"><Reveal><p className="kicker">05 — FROM THE PARENTS</p><h2>When a school chooses <em>your child.</em></h2></Reveal><div className="review-grid">{reviews.map(([name,role,text],i)=><Reveal key={name} delay={i*.08}><article className="review"><Quote size={25}/><p>“{text}”</p><div><strong>{name}</strong><small>{role}</small></div></article></Reveal>)}</div></div></section>}

export function CTA(){return <section className="cta"><div className="container cta-inner"><Reveal><p className="kicker light">ADMISSIONS OPEN · 2027 · CLASS IV–XII</p><h2>Ready to discover<br/><em>what’s possible?</em></h2><a className="button light-button" href="https://admission.tis.edu.in/" target="_blank" rel="noreferrer">Apply to Tulas <ArrowUpRight/></a></Reveal></div></section>}

export function Footer(){return <footer><div className="container footer-grid"><div><a className="brand footer-brand" href="#top"><span className="brand-mark">T</span><span>TULAS<br/><small>INTERNATIONAL SCHOOL</small></span></a><p className="footer-copy">A co-educational boarding and day school in Dehradun, Uttarakhand.</p></div><div><h4>Explore</h4><a href="#about">About TIS</a><a href="#academics">Academics</a><a href="#life">Boarding Life</a><a href="#sports">Beyond Academics</a></div><div><h4>Contact</h4><p>Dhoolkot, P.O – Selaqui,<br/>Chakrata Road, Dehradun-248011</p><a href="tel:+919837983791">+91 98379 83791</a><a href="mailto:info@tis.edu.in">info@tis.edu.in</a></div><div><h4>Admissions</h4><p>For enquiries and applications, visit the official admission portal.</p><a className="footer-apply" href="https://admission.tis.edu.in/" target="_blank" rel="noreferrer">Apply now <ArrowUpRight/></a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Tulas International School</span><span>Homepage redesign assessment</span></div></footer>}
